import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#ffb3ac',
        'primary-container': '#d32f2f',
        'on-primary': '#680008',
        'on-primary-container': '#fff2f0',
        'secondary': '#ddc1b7',
        'secondary-container': '#56423b',
        'on-secondary': '#3e2c26',
        'on-secondary-container': '#cbafa6',
        'tertiary': '#c8c8b0',
        'tertiary-container': '#70715d',
        'on-tertiary': '#303221',
        'on-tertiary-container': '#f6f6dd',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-variant': '#353535',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1c1c',
        'surface-container': '#202020',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'surface-tint': '#ffb3ac',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e4beba',
        'outline': '#ab8985',
        'outline-variant': '#5b403d',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#303030',
        'inverse-primary': '#ba1a20',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['"Work Sans"', 'sans-serif'],
        label: ['"Work Sans"', 'sans-serif'],
        sans: ['"Work Sans"', 'sans-serif'],
        serif: ['"Noto Serif"', 'serif'],
      },
    },
  },
  plugins: [],
} satisfies Config;
